#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SYSTEM PACKAGES
#
apt-get update
apt-get remove ruby1.8
xargs apt-get install -y --force-yes < /build/packages.txt
apt-get clean

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

# Ruby buildpack system configuration
mkdir /tmp/ruby && cd /tmp/ruby
curl --progress ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p353.tar.gz | tar xz
cd ruby-2.0.0-p353
./configure --disable-install-rdoc
make
make install
update-alternatives --set ruby /usr/bin/ruby2.0.0
update-alternatives --set gem /usr/bin/gem2.0.0
gem install bundler
cd /build/buildpacks/heroku-buildpack-ruby && bundle install
